### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by YueWenqiang** [colorfulandcjy0806/Citrus-YOLOv7#1]
您好，感谢您分享宝贵的代码。请问可以麻烦分享一下您论文提到的训练集和测试集吗？万分感谢。
邮箱：yuewenqiang2021@163.com

**Comment by colorfulandcjy0806** [comment]
The dataset for this article has been handed over to my undergraduate supervisor. Thank you very much for your attention to the work of this article!
Professor Chen, email: chenxy@sicau.edu.cn
